import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import {
  faShoppingCart,
  faUserCircle,
  faSearch,
  faDollarSign,
  faBookmark as fasBookmark,
  faCartPlus,
  faPlus,
  faMinus,
  faTrashAlt,
  faLongArrowAltLeft,
  faCreditCard,
  faFileAlt,
  faInfoCircle,
  faPen,
  faStar as fasStar,
  faStarHalfAlt,
  faCheckCircle as fasCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faHeart,
  faEye,
  faPencilAlt,
  faEllipsisH,
  faExclamation,
  faCheck,
} from '@fortawesome/free-solid-svg-icons'

import {
  faCheckCircle as farCheckCircle,
  faBookmark as farBookmark,
  faHeart as farHeart,
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  fab,
  faChevronDown,
  faShoppingCart,
  faUserCircle,
  faSearch,
  faDollarSign,
  fasBookmark,
  farBookmark,
  faCartPlus,
  faPlus,
  faMinus,
  faTrashAlt,
  faLongArrowAltLeft,
  faCreditCard,
  faFileAlt,
  faInfoCircle,
  faPen,
  fasStar,
  faStarHalfAlt,
  fasCheckCircle,
  farCheckCircle,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faHeart,
  faEye,
  farHeart,
  faPencilAlt,
  faEllipsisH,
  farStar,
  faExclamation,
  faCheck
)
