import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faShoppingCart,
  faUserCircle,
  faSearch,
  faDollarSign,
  faBookmark,
  faCartPlus,
  faPlus,
  faMinus,
  faTrashAlt,
  faLongArrowAltLeft,
  faCreditCard,
  faFileAlt,
  faInfoCircle,
  faPen,
  faStar,
  faStarHalfAlt,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faHeart,
  faEye,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faShoppingCart,
  faUserCircle,
  faSearch,
  faDollarSign,
  faBookmark,
  faCartPlus,
  faPlus,
  faMinus,
  faTrashAlt,
  faLongArrowAltLeft,
  faCreditCard,
  faFileAlt,
  faInfoCircle,
  faPen,
  faStar,
  faStarHalfAlt,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faHeart,
  faEye,
)
