import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import {
  faShoppingCart,
  faUserCircle,
  faSearch,
  faDollarSign,
  faBookmark as fasBookmark,
  faCartPlus,
  faPlus,
  faMinus,
  faTrashAlt,
  faLongArrowAltLeft,
  faCreditCard,
  faFileAlt,
  faInfoCircle,
  faPen,
  faStar,
  faStarHalfAlt,
  faCheckCircle as fasCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faHeart,
  faEye,
} from '@fortawesome/free-solid-svg-icons'

import {
  faCheckCircle as farCheckCircle,
  faBookmark as farBookmark,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  fab,
  faChevronDown,
  faShoppingCart,
  faUserCircle,
  faSearch,
  faDollarSign,
  farBookmark,
  fasBookmark,
  faCartPlus,
  faPlus,
  faMinus,
  faTrashAlt,
  faLongArrowAltLeft,
  faCreditCard,
  faFileAlt,
  faInfoCircle,
  faPen,
  faStar,
  faStarHalfAlt,
  fasCheckCircle,
  farCheckCircle,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faHeart,
  faEye
)
